tetdt

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -29,19 +29,19 @@ jobs:
           cat coding-style-reports.log
       - name: coding style
         run: |
-          IFS=
           while IFS= read -r line; do
-            error="$(echo $line | cut -d ' ' -f 2)"
-            file="$(echo $line | cut -d ' ' -f 1)"
-            type="$(echo $error | cut -d ':' -f 1)"
-            code="$(echo $error | cut -d ':' -f 2)"
-            line="$(echo $file | cut -d ':' -f 2)"
-            filename="$(echo $file | cut -d ':' -f 1)"
-            echo "::error file=$filename,line=$line,title=$type coding style error: $filename::$code"
+            file=$(echo "$line" | awk -F ':' '{print $1}')
+            line_number=$(echo "$line" | awk -F ':' '{print $2}')
+            error=$(echo "$line" | awk -F ':' '{print $3}')
+            type=$(echo "$error" | awk '{print $1}')
+            code=$(echo "$error" | awk '{print $2}')
+            echo "::error file=$file,line=$line_number,title=$type coding style error: $file::$code"
           done < coding-style-reports.log
-          if [[ "$(du -b coding-style-reports.log | cut -d ' ' -f 1)" != "0" ]]; then
-            echo ::exit::failure
+          if [[ -s coding-style-reports.log ]]; then
+            echo "::error 'coding-style-reports.log is not empty'"
+            exit 1
           fi
+
 
   check_program_compilation:
     runs-on: ubuntu-latest
@@ -92,5 +92,5 @@ jobs:
         with:
           target_repo_url: ${{ env.MIRROR_URL }}
           ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
-          
+
           
